config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :concerts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "groups#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concert.rb
class Concert < ApplicationRecord
    belongs_to :group

    def group_name
        self.group.name
    end

end

app/models/group.rb
class Group < ApplicationRecord
    has_many :concerts, dependent: :destroy
    enum group_type: [:Boygroup, :GirlsGroup, :Band]

    def cant_concert
        self.concerts.count
    end

    def concert_moth
        this_month = Time.now.month
        self.concerts.select{|m| m.date.month == this_month}.count
    end

    def concert_last
        #self.concerts.map{|c| c.date }.last.strftime("%Y %B %A")
        aux = self.concerts.map{|c| c.date }.last
        if aux.nil?
            aux = " "
        else
            aux.strftime("%Y %B %A")
        end
    end

    def attendance_max
        self.concerts.map{|c| c.attendance}.max
    end

    def duration_max
        self.concerts.map{|c| c.duration}.max
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[ show edit update destroy ]

  # GET /concerts or /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1 or /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
    @groups = Group.all
  end

  # GET /concerts/1/edit
  def edit
    @groups = Group.all
  end

  # POST /concerts or /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to concerts_path, notice: "Concierto creado en forma correcta." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1 or /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to concert_url(@concert), notice: "Concierto actualizado en forma correcta." }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1 or /concerts/1.json
  def destroy
    @concert.destroy

    respond_to do |format|
      format.html { redirect_to concerts_url, notice: "Concierto fue borrado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:attendance, :duration, :place, :date, :group_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    #@groups = Group.all
    @groups = Group.eager_load(:concerts)#Para que haga una gran consulta de group y conciertos
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @tipo_grupo = Group.group_types.keys
  end

  # GET /groups/1/edit
  def edit
    @tipo_grupo = Group.group_types.keys
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "El Grupo fue creado." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "El Grupo fue actualizado." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "El Grupo fue Borrado en forma correcta." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :crew, :debut_date, :group_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/concerts/_concert.html.erb
<div id="<%= dom_id concert %>">

<div class="mb-3 row form-control-lg" >
  <label class="col-sm-2 col-form-label">Nombre del Grupo</label>
  <div class="col-sm-10">
    <%= concert.group_name %>
  </div>
</div>


<div class="mb-3 row form-control-lg" >
  <label class="col-sm-2 col-form-label">Num de Personas</label>
  <div class="col-sm-10">
    <%= concert.attendance %>
  </div>
</div>


<div class="mb-3 row form-control-lg" >
  <label class="col-sm-2 col-form-label">Duración (hrs)</label>
  <div class="col-sm-10">
    <%= concert.duration %>
  </div>
</div>

<div class="mb-3 row form-control-lg" >
  <label class="col-sm-2 col-form-label">Lugar</label>
  <div class="col-sm-10">
    <%= concert.place %>
  </div>
</div>

<div class="mb-3 row form-control-lg" >
  <label class="col-sm-2 col-form-label">Fecha</label>
  <div class="col-sm-10">
    <%= concert.date %>
  </div>
</div>

</div>

app/views/concerts/_form.html.erb
<%= form_with(model: concert) do |form| %>
  <% if concert.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
        <% concert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 row form-control-lg" >
    <label class="col-sm-2 col-form-label">Nombre del Grupo</label>
    <div class="col-sm-10">
      <% group_id = @concert.group_id %> 
      <%= form.select :group_id, options_from_collection_for_select(@groups, :id, :name, group_id ) %>
    </div>
  </div>

  <div class="mb-3 row form-control-lg" >
    <label class="col-sm-2 col-form-label">Num de Personas</label>
    <div class="col-sm-10">
      <%= form.number_field :attendance %>
    </div>
  </div>

  <div class="mb-3 row form-control-lg" >
    <label class="col-sm-2 col-form-label">Duración (hrs)</label>
    <div class="col-sm-10">
      <%= form.number_field :duration %>
    </div>
  </div>

  <div class="mb-3 row form-control-lg" >
    <label class="col-sm-2 col-form-label">Lugar</label>
    <div class="col-sm-10">
      <%= form.text_field :place %>
    </div>
  </div>

  <div class="mb-3 row form-control-lg" >
    <label class="col-sm-2 col-form-label">Fecha</label>
    <div class="col-sm-10">
      <%= form.datetime_field :date %>
    </div>
  </div>

 <div>
    <%= form.submit %>
 </div>
<% end %>

app/views/concerts/edit.html.erb
<br>
<h1>Editar Concierto</h1>
<br>

<%= render "form", concert: @concert %>
<br>
<button style="border-radius: 60px; float: left;" >
  <%= link_to "Listar Conciertos", concerts_path, class: "btn btn-inverse" %>
</button>

app/views/concerts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Conciertos</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Cantidad de Personas</th>
      <th scope="col">Duracion</th>
      <th scope="col">Lugar</th>
      <th scope="col">Fecha</th>      
      <th scope="col">Banda</th>      
      <th scope="col"></th>      
    </tr>
  </thead>
  <tbody>
    <% @concerts.each do |concert| %>
      <tr>      
        <td><%= concert.attendance%></td>
        <td><%= concert.duration %></td>
        <td><%= concert.place %></td>
        <td><%= concert.date %></td>
        <td><%= concert.group_name %></td>
        <td>
          <button style="border-radius: 60px; float: left;" >
            <%= link_to "Editar", edit_concert_path(concert), class: "btn btn-inverse" %>
          </button>
        </td>
        <td>
          <%= button_to "Eliminar", concert, method: :delete %>
        </td>        
      </tr>      
    <% end %>

  </tbody>
</table>

app/views/concerts/new.html.erb
<br>
<h1>Nuevo Concierto</h1>
<br>

<%= render "form", concert: @concert %>

<br>
<button style="border-radius: 60px; float: left;" >
  <%= link_to "Lista de Conciertos", concerts_path, class: "btn btn-inverse" %>
</button>

app/views/concerts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @concert %>

<div>

  <button style="border-radius: 60px; float: left;" >
    <%= link_to "Editar", edit_concert_path(@concert) , class: "btn btn-inverse" %>
  </button>

  <button style="border-radius: 60px; float: left;" >
    <%= link_to "Listar Conciertos", concerts_path , class: "btn btn-inverse" %>
  </button>

  <%= button_to "Eliminar", @concert, method: :delete , class: "btn btn-inverse" %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3 row form-control-lg" >
    <label class="col-sm-2 col-form-label">Nombre </label>
    <div class="col-sm-10">
      <%= form.text_field :name %>
    </div>
  </div>

  <div class="mb-3 row form-control-lg" >
    <label class="col-sm-2 col-form-label">Num de Integrantes </label>
    <div class="col-sm-10">
      <%= form.number_field :crew, style: "width: 100px;" %>
    </div>
  </div>

  <div class="mb-3 row form-control-lg" >
    <label class="col-sm-2 col-form-label">Dia Debut</label>
    <div class="col-sm-10">
      <%= form.date_field :debut_date %>
    </div>
  </div>

  <div class="mb-3 row form-control-lg" >
    <label class="col-sm-2 col-form-label">Tipo Grupo</label>
    <div class="col-sm-10">
      <%= form.select :group_type, options_for_select(@tipo_grupo) %>
    </div>
  </div>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <h3>
      <strong>Grupo:</strong>
      <%= group.name %>
    </h3>
  </p>

  <table class="table">
    <tbody>
      <tr>
        <td>
          <strong>Num de Integrantes : </strong>
          <%= group.crew %>
        </td>
        <td>
          <strong>Fecha del Debut : </strong>
          <%= group.debut_date %>
        </td>
        <td>
          <strong>Tipo de Grupo : </strong>
          <%= group.group_type %>
        </td>      

        <% if group.cant_concert != 0 %>
        <!-- Mostrar los conciertos -->
          <td>
            <strong>Conciertos <%= group.cant_concert %> </strong>
            <ul>
              <% group.concerts.each do |concert| %>
                <li>
                  Lugar:<%= concert.place %>, Personas:<%= concert.attendance %>
                </li>
              <% end %>
            </ul>
          </td>
          <% end %>
      </tr>
     </tbody>
  </table>


  <% if group.cant_concert != 0 %>
  <!-- Mostrar los conciertos -->  
  <table class="table" >
      <thead>
        <tr align="center">
          <th scope="col">Conciertos del Mes</th>
          <th scope="col">Último concierto</th>
          <th scope="col">Duracion maxima Hrs</th>
          <th scope="col">Publico maximo</th>
        </tr>
      </thead>
      <tbody>
        <tr align="center">
          <td><%= group.concert_moth %></td>
          <td><%= group.concert_last %></td>
          <td><%= group.duration_max %></td>
          <td><%= group.attendance_max %></td>      
        </tr>
      </tbody>
  
    </table>
  <% end %>
</div>

app/views/groups/edit.html.erb
<br>
<h1>Editar Grupo</h1>
<br>
<%= render "form", group: @group %>

<br>

<div>

  <button style="border-radius: 60px; float: left; padding: 3px 5px;">
    <%= link_to "Mostrar", @group, class: "btn btn-inverse" %>
  </button>

  <button style="border-radius: 60px; float: left; padding: 3px 5px;">
    <%= link_to "Listar Grupo", groups_path, class: "btn btn-inverse" %>
  </button>

  <!--
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
  -->

</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<!-- <h1>Grupos</h1> -->

<div id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
    
    <button style="border-radius: 60px; float: right;" >
      <%= link_to "Mostrar el grupo", group, class: "btn btn-inverse" %>
    </button>
    <br><br>
  <% end %>
</div>

app/views/groups/new.html.erb
<br>
<h1>Nuevo Grupo</h1>
<br>
<%= render "form", group: @group %>

<br>


<button style="border-radius: 60px; float: left; padding: 3px 5px;">
  <%= link_to "Listar Grupo", groups_path, class: "btn btn-inverse" %>
</button>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>

  <button style="border-radius: 60px; float: right; padding: 3px 5px;" >
    <%= link_to "Editar", edit_group_path(@group), class: "btn btn-inverse" %>
  </button>

  <button style="border-radius: 60px; float: left; padding: 3px 5px;">
    <%= link_to "Listar grupos", groups_path, class: "btn btn-inverse" %>
  </button>
  
  <%= button_to "Eliminar", @group, method: :delete, class: "btn btn-inverse" %>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductoraDeEventos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </head>

  <body>
    <div class="container">


    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <div class="container-fluid">
      <a class="navbar-brand" href="#">PRODUCTORA</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Grupos
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="/groups">Listar</a></li>
              <li><a class="dropdown-item" href="/groups/new">Nuevo</a></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Conciertos
            </a>            
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="/concerts">Listar</a></li>
              <li><a class="dropdown-item" href="/concerts/new">Nuevo</a></li>
            </ul>            
          </li>
 
        </ul>

      </div>
    </div>
    </nav>








      <%= yield %>
    </div>
  </body>
</html>